[package]
name = "cargo-ui"
version = "0.3.0"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
build = "build.rs"
license = "GPL-3.0-only"
description = "GUI for cargo"
categories = ["development-tools::cargo-plugins"]
keywords = ["cargo", "ui", "gui"]
repository = "https://github.com/sixtyfpsui/cargo-ui"
resolver = "2"

[features]
x11 = ["sixtyfps/x11"]
wayland = ["sixtyfps/wayland"]
sixtyfps-backend-qt = ["sixtyfps/backend-qt"]
sixtyfps-backend-gl = ["sixtyfps/backend-qt"]
default = ["x11", "wayland", "sixtyfps-backend-qt", "sixtyfps-backend-gl"]

[dependencies]
sixtyfps = { version = "0.1.4", default-features = false }
tokio = { version = "1.12.0", features= ["full"] }
futures = "0.3"
cargo_metadata = "0.14"
serde_json = "1"
serde = "1"
dunce = "1"
itertools = "0.10"
shlex = "1"
open = "2"
crates-index = { version = "0.18.0" }
toml_edit = "0.6.0"
anyhow = "1"
rfd = { version = "0.7", default-features = false, features = [ "parent" ] }

[build-dependencies]
sixtyfps-build = { version = "0.1.4" }

