[package]
name = "cargo-ui"
version = "0.3.2"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
build = "build.rs"
license = "GPL-3.0-only"
description = "GUI for cargo"
categories = ["development-tools::cargo-plugins"]
keywords = ["cargo", "ui", "gui"]
repository = "https://github.com/slint-ui/cargo-ui"
resolver = "2"

[features]
slint-backend-qt = ["slint/backend-qt"]
slint-backend-gl-all = ["slint/backend-winit", "slint/renderer-winit-femtovg"]
slint-backend-gl-wayland = ["slint/backend-winit-wayland", "slint/renderer-winit-femtovg"]
slint-backend-gl-x11 = ["slint/backend-winit-x11", "slint/renderer-winit-femtovg"]

default = ["slint-backend-qt", "slint-backend-gl-all"]

[dependencies]
anyhow = "1.0.53"
cargo_metadata = "0.15"
crates-index = { version = "0.19.0" }
dunce = "1.0.2"
futures = "0.3"
itertools = "0.10"
open = "4.0"
rfd = { version = "0.11", default-features = false, features = [ "xdg-portal" ] }
serde = "1.0.136"
serde_json = "1.0.78"
shlex = "1.1"
slint = { version = "1", default-features = false, features = [ "compat-1-0" ] }
tokio = { version = "1.24.2", features= ["full"] }
toml_edit = "0.19.0"
git2 = "0.16.1"

[build-dependencies]
slint-build = { version = "1" }

